import type { IndustryProfile } from "./types.js";

/**
 * The industry catalogue.
 *
 * UK codes are SIC 2007, taken from the Companies House condensed SIC list
 * (https://resources.companieshouse.gov.uk/sic/). A company's SIC code is
 * self-declared at incorporation, so it is treated as strong-but-not-certain
 * evidence: `classify()` records SIC matches as HIGH confidence and keyword
 * matches as MEDIUM, and both are stored with the evidence that produced them.
 *
 * `commercialWeight` is a judgement about how much a website is worth to the
 * sector, not a claim about any individual company.
 */
export const INDUSTRIES: IndustryProfile[] = [
  {
    key: "dental",
    label: "Clínicas odontológicas",
    group: "Saúde",
    registryCodes: { GB: ["86230"], BR: ["8630504"] },
    keywords: [
      "dental",
      "dentist",
      "dentistry",
      "orthodont",
      "endodont",
      "periodont",
    ],
    negativeKeywords: [
      "dental supplies",
      "dental laboratory",
      "dental equipment",
      "manufactur",
    ],
    subIndustries: [
      {
        key: "general_dentistry",
        label: "Clínica geral",
        keywords: ["dental practice", "family dentist"],
      },
      {
        key: "cosmetic_dentistry",
        label: "Estética dental",
        keywords: ["cosmetic", "veneer", "whitening", "smile"],
      },
      { key: "implants", label: "Implantes", keywords: ["implant"] },
      {
        key: "orthodontics",
        label: "Ortodontia",
        keywords: ["orthodont", "invisalign", "braces"],
      },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: [
      "Clínica geral",
      "Implantes",
      "Estética dental",
      "Ortodontia",
      "Atendimento de urgência",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Prontuário e histórico do paciente",
      "Agenda por profissional e sala",
      "Orçamentos e planos de tratamento",
      "Convênios e repasses",
    ],
  },
  {
    key: "aesthetic_clinic",
    label: "Clínicas de estética",
    group: "Saúde",
    registryCodes: { GB: ["86900", "96020", "96040"], BR: ["9602502"] },
    keywords: [
      "aesthetic",
      "aesthetics",
      "skin clinic",
      "botox",
      "dermal filler",
      "cosmetic clinic",
      "medspa",
      "med spa",
    ],
    negativeKeywords: ["aesthetic design", "aesthetic studio photography"],
    subIndustries: [
      {
        key: "injectables",
        label: "Injetáveis",
        keywords: ["botox", "filler", "toxin"],
      },
      {
        key: "skin",
        label: "Tratamentos de pele",
        keywords: ["skin", "peel", "facial", "microneedl"],
      },
      {
        key: "laser",
        label: "Tratamentos a laser",
        keywords: ["laser", "ipl"],
      },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: [
      "Consultas",
      "Tratamentos injetáveis",
      "Tratamentos de pele",
      "Tratamentos a laser",
      "Pós-atendimento",
    ],
    systemWeight: 0.75,
    systemUseCases: [
      "Ficha de anamnese e evolução",
      "Agenda e pacotes de sessões",
      "Estoque de insumos",
      "Comissão por profissional",
    ],
  },
  {
    key: "medical_practice",
    label: "Consultórios médicos",
    group: "Saúde",
    registryCodes: {
      GB: ["86210", "86220"],
      BR: ["8630501", "8630502", "8630503"],
    },
    keywords: [
      "clinic",
      "private gp",
      "medical practice",
      "surgery",
      "consultant",
    ],
    negativeKeywords: ["veterinary", "dental"],
    subIndustries: [
      {
        key: "private_gp",
        label: "Clínico geral",
        keywords: ["private gp", "general practice"],
      },
      {
        key: "specialist",
        label: "Especialidades",
        keywords: ["consultant", "specialist"],
      },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ["Agendamento", "Check-ups", "Encaminhamentos", "Valores"],
    systemWeight: 0.8,
    systemUseCases: [
      "Prontuário eletrônico",
      "Agenda e confirmação de consulta",
      "Faturamento de convênios",
    ],
  },
  {
    key: "physiotherapy",
    label: "Clínicas de fisioterapia",
    group: "Saúde",
    registryCodes: { GB: ["86900"], BR: ["8650004", "8650003"] },
    keywords: [
      "physio",
      "physiotherapy",
      "sports injury",
      "osteopath",
      "chiropract",
      "rehabilitation",
    ],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "sports",
        label: "Lesões esportivas",
        keywords: ["sports injury", "sports therapy"],
      },
      {
        key: "musculoskeletal",
        label: "Musculoesquelética",
        keywords: ["back pain", "msk", "joint"],
      },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Avaliação inicial",
      "Planos de tratamento",
      "Reabilitação esportiva",
      "Agendar consulta",
    ],
    systemWeight: 0.75,
    systemUseCases: [
      "Evolução por sessão",
      "Pacotes e frequência",
      "Agenda por profissional",
    ],
  },
  {
    key: "legal",
    label: "Escritórios de advocacia",
    group: "Serviços profissionais",
    registryCodes: { GB: ["69101", "69102", "69109"], BR: ["6911701"] },
    keywords: [
      "solicitor",
      "solicitors",
      "law firm",
      "legal",
      "barrister",
      "conveyanc",
    ],
    negativeKeywords: ["legal high", "legal services software"],
    subIndustries: [
      {
        key: "conveyancing",
        label: "Imobiliário",
        keywords: ["conveyanc", "property law"],
      },
      {
        key: "family",
        label: "Família",
        keywords: ["family law", "divorce"],
      },
      {
        key: "immigration",
        label: "Imigração",
        keywords: ["immigration", "visa"],
      },
      {
        key: "personal_injury",
        label: "Danos e indenizações",
        keywords: ["personal injury", "accident claim"],
      },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Áreas de atuação",
      "Serviços com valor fechado",
      "Primeira consulta gratuita",
      "Equipe",
    ],
    systemWeight: 0.9,
    systemUseCases: [
      "Processos, prazos e andamentos",
      "Documentos por cliente",
      "Horas e honorários",
      "Agenda de audiências",
    ],
  },
  {
    key: "accounting",
    label: "Escritórios de contabilidade",
    group: "Serviços profissionais",
    registryCodes: { GB: ["69201", "69202", "69203"], BR: ["6920601"] },
    keywords: [
      "accountant",
      "accountants",
      "accountancy",
      "bookkeep",
      "tax advis",
      "chartered",
    ],
    negativeKeywords: ["accounting software"],
    subIndustries: [
      { key: "tax", label: "Tributário", keywords: ["tax"] },
      {
        key: "bookkeeping",
        label: "Escrituração",
        keywords: ["bookkeep", "payroll"],
      },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Serviços e valores",
      "Consulta gratuita",
      "Obrigações fiscais",
      "Área do cliente",
    ],
    systemWeight: 0.9,
    systemUseCases: [
      "Obrigações por cliente e vencimento",
      "Documentos recebidos",
      "Honorários recorrentes",
    ],
  },
  {
    key: "real_estate",
    label: "Imobiliárias",
    group: "Imobiliário",
    registryCodes: {
      GB: ["68310", "68320"],
      BR: ["6821801", "6821802", "6822600"],
    },
    keywords: [
      "estate agent",
      "lettings",
      "letting agent",
      "property management",
      "realtor",
    ],
    negativeKeywords: [],
    subIndustries: [
      { key: "sales", label: "Vendas", keywords: ["for sale", "sales"] },
      { key: "lettings", label: "Locação", keywords: ["letting", "rental"] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: [
      "Avaliação gratuita",
      "Imóveis à venda",
      "Imóveis para alugar",
      "Serviços ao proprietário",
    ],
    systemWeight: 0.85,
    systemUseCases: [
      "Carteira de imóveis e fotos",
      "Visitas agendadas",
      "Propostas e contratos",
      "Repasse de aluguel",
    ],
  },
  {
    key: "construction",
    label: "Construtoras",
    group: "Obras e manutenção",
    registryCodes: {
      GB: ["41201", "41202", "43120", "43110", "43999"],
      BR: ["4120400", "4399101", "4399103", "4399199", "4299599"],
    },
    keywords: [
      "construction",
      "builders",
      "building services",
      "contractors",
      "renovation",
      "extension",
      "loft conversion",
    ],
    negativeKeywords: ["building society", "construction software"],
    subIndustries: [
      {
        key: "extensions",
        label: "Ampliações e reformas",
        keywords: ["extension", "loft conversion"],
      },
      {
        key: "newbuild",
        label: "Obra nova",
        keywords: ["new build", "development"],
      },
      {
        key: "refurbishment",
        label: "Retrofit",
        keywords: ["refurbish", "renovation"],
      },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Obras recentes",
      "Orçamento gratuito",
      "Certificações",
      "Área de atendimento",
    ],
    systemWeight: 0.95,
    systemUseCases: [
      "Ordens de serviço e etapas",
      "Medição e diário de obra",
      "Orçado x realizado",
      "Equipes e alocação",
    ],
  },
  {
    key: "roofing",
    label: "Coberturas e telhados",
    group: "Obras e manutenção",
    registryCodes: { GB: ["43910"] },
    keywords: ["roofing", "roofer", "roofs", "flat roof", "guttering"],
    negativeKeywords: ["roofing supplies", "roofing wholesale"],
    subIndustries: [
      {
        key: "flat_roofing",
        label: "Laje e cobertura plana",
        keywords: ["flat roof", "epdm", "grp"],
      },
      {
        key: "pitched_roofing",
        label: "Telhado inclinado",
        keywords: ["tile", "slate", "pitched"],
      },
    ],
    commercialWeight: 0.95,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Reparos de telhado",
      "Telhados novos",
      "Atendimento de urgência",
      "Vistoria gratuita",
      "Garantias",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Ordens de serviço",
      "Orçamento e visita técnica",
      "Garantias",
    ],
  },
  {
    key: "plumbing",
    label: "Hidráulica",
    group: "Obras e manutenção",
    registryCodes: { GB: ["43220"], BR: ["4322301"] },
    keywords: ["plumbing", "plumber", "bathroom installation", "drainage"],
    negativeKeywords: ["plumbing supplies", "plumbing merchants", "wholesale"],
    subIndustries: [
      {
        key: "emergency",
        label: "Emergência",
        keywords: ["emergency", "24 hour", "24/7"],
      },
      {
        key: "bathrooms",
        label: "Instalação de banheiros",
        keywords: ["bathroom"],
      },
    ],
    commercialWeight: 0.9,
    highTicket: false,
    bookingExpected: false,
    typicalServices: [
      "Atendimento de urgência",
      "Instalação de banheiros",
      "Reparo de vazamentos",
      "Área de atendimento",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Ordens de serviço e urgências",
      "Roteiro das equipes",
      "Orçamento no local",
    ],
  },
  {
    key: "heating_hvac",
    label: "Climatização e refrigeração",
    group: "Obras e manutenção",
    registryCodes: { GB: ["43220"], BR: ["4322302"] },
    keywords: [
      "heating",
      "boiler",
      "hvac",
      "air conditioning",
      "gas safe",
      "heat pump",
      "underfloor heating",
    ],
    negativeKeywords: ["heating supplies", "wholesale"],
    subIndustries: [
      {
        key: "boilers",
        label: "Instalação de aquecimento",
        keywords: ["boiler"],
      },
      {
        key: "heat_pumps",
        label: "Bombas de calor",
        keywords: ["heat pump", "air source", "ground source"],
      },
      {
        key: "air_conditioning",
        label: "Ar-condicionado",
        keywords: ["air conditioning", "aircon"],
      },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Instalação de aquecimento",
      "Manutenção e reparos",
      "Orçamento gratuito",
      "Parcelamento",
      "Certificações",
    ],
    systemWeight: 0.85,
    systemUseCases: [
      "Ordens de serviço e manutenção preventiva",
      "Contratos por equipamento",
      "Histórico por cliente",
    ],
  },
  {
    key: "electrician",
    label: "Eletricistas",
    group: "Obras e manutenção",
    registryCodes: { GB: ["43210"], BR: ["4321500"] },
    keywords: [
      "electrical",
      "electrician",
      "electrics",
      "rewire",
      "ev charger",
    ],
    negativeKeywords: ["electrical wholesale", "electrical manufacturing"],
    subIndustries: [
      {
        key: "domestic",
        label: "Elétrica residencial",
        keywords: ["domestic", "rewire"],
      },
      {
        key: "ev_charging",
        label: "Carregadores elétricos",
        keywords: ["ev charger", "electric vehicle"],
      },
    ],
    commercialWeight: 0.9,
    highTicket: false,
    bookingExpected: false,
    typicalServices: [
      "Elétrica residencial",
      "Laudos e certificados",
      "Instalação de carregadores",
      "Atendimento de urgência",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Ordens de serviço",
      "Laudos e certificados",
      "Roteiro das equipes",
    ],
  },
  {
    key: "joinery",
    label: "Marcenaria e carpintaria",
    group: "Obras e manutenção",
    registryCodes: { GB: ["43320"], BR: ["4330402", "3101200"] },
    keywords: [
      "joinery",
      "carpenter",
      "carpentry",
      "bespoke furniture",
      "fitted wardrobes",
      "kitchen fitting",
    ],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "bespoke",
        label: "Móveis sob medida",
        keywords: ["bespoke", "made to measure"],
      },
    ],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Móveis sob medida",
      "Cozinhas e armários planejados",
      "Galeria de projetos",
      "Visita de projeto gratuita",
    ],
    systemWeight: 0.75,
    systemUseCases: [
      "Projeto e medição",
      "Etapas de produção",
      "Entrega e montagem",
    ],
  },
  {
    key: "plastering_decorating",
    label: "Pintura e acabamento",
    group: "Obras e manutenção",
    registryCodes: {
      GB: ["43310", "43341", "43342", "43330"],
      BR: ["4330404", "4399103"],
    },
    keywords: [
      "plastering",
      "plasterer",
      "decorator",
      "painting and decorating",
      "rendering",
      "glazing",
      "flooring",
    ],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "plastering",
        label: "Reboco e gesso",
        keywords: ["plaster", "render"],
      },
      {
        key: "decorating",
        label: "Pintura",
        keywords: ["decorat", "painting"],
      },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: false,
    typicalServices: [
      "Serviços",
      "Trabalhos recentes",
      "Orçamento gratuito",
      "Área de atendimento",
    ],
    systemWeight: 0.6,
    systemUseCases: ["Ordens de serviço", "Orçamento por metragem"],
  },
  {
    key: "landscaping",
    label: "Paisagismo e jardinagem",
    group: "Obras e manutenção",
    registryCodes: { GB: ["81300"] },
    keywords: [
      "landscap",
      "garden",
      "groundwork",
      "driveway",
      "paving",
      "tree surgeon",
    ],
    negativeKeywords: ["garden centre"],
    subIndustries: [
      { key: "design", label: "Projeto de jardim", keywords: ["design"] },
      {
        key: "driveways",
        label: "Pisos e calçadas",
        keywords: ["driveway", "paving", "patio"],
      },
    ],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Projeto de jardim",
      "Pisos e áreas externas",
      "Galeria de projetos",
      "Visita técnica gratuita",
    ],
    systemWeight: 0.7,
    systemUseCases: ["Ordens de serviço e rotas", "Contratos de manutenção"],
  },
  {
    key: "cleaning",
    label: "Empresas de limpeza",
    group: "Serviços",
    registryCodes: {
      GB: ["81210", "81221", "81222", "81229", "81299"],
      BR: ["8121400"],
    },
    keywords: [
      "cleaning",
      "cleaners",
      "domestic cleaning",
      "commercial cleaning",
      "end of tenancy",
    ],
    negativeKeywords: [
      "dry cleaning",
      "cleaning products",
      "cleaning supplies",
    ],
    subIndustries: [
      {
        key: "commercial",
        label: "Limpeza comercial",
        keywords: ["commercial", "office cleaning"],
      },
      {
        key: "domestic",
        label: "Limpeza residencial",
        keywords: ["domestic", "house cleaning"],
      },
      {
        key: "end_of_tenancy",
        label: "Limpeza pós-obra e desocupação",
        keywords: ["end of tenancy", "move out"],
      },
    ],
    commercialWeight: 0.75,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Serviços e valores",
      "Orçamento na hora",
      "Área de atendimento",
      "Seguro e checagem de equipe",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Escala de equipes e rotas",
      "Contratos e postos",
      "Checklist por posto",
    ],
  },
  {
    key: "auto_repair",
    label: "Oficinas mecânicas",
    group: "Automotivo",
    registryCodes: { GB: ["45200"], BR: ["4520001", "4520002"] },
    keywords: ["garage", "mot", "car repair", "servicing", "bodyshop", "tyres"],
    negativeKeywords: ["garage doors", "car sales"],
    subIndustries: [
      {
        key: "mot_servicing",
        label: "Revisão e manutenção",
        keywords: ["mot", "service"],
      },
      {
        key: "bodywork",
        label: "Funilaria",
        keywords: ["bodyshop", "body repair"],
      },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Agendar revisão",
      "Manutenção",
      "Reparos",
      "Valores",
      "Como chegar",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Ordem de serviço e orçamento",
      "Peças e estoque",
      "Histórico por veículo",
    ],
  },
  {
    key: "barber",
    label: "Barbearias",
    group: "Beleza e cuidados",
    registryCodes: { GB: ["96020"], BR: ["9602501"] },
    keywords: ["barber", "barbers", "barbershop", "grooming"],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "traditional",
        label: "Barbearia tradicional",
        keywords: ["traditional", "hot towel"],
      },
    ],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Tabela de preços",
      "Agendar on-line",
      "Horário de funcionamento",
      "Como chegar",
    ],
    systemWeight: 0.45,
    systemUseCases: ["Agenda on-line", "Comissão por profissional"],
  },
  {
    key: "beauty_salon",
    label: "Salões de beleza",
    group: "Beleza e cuidados",
    registryCodes: { GB: ["96020", "96040"], BR: ["9602501", "9602502"] },
    keywords: [
      "salon",
      "beauty",
      "hairdress",
      "nails",
      "lashes",
      "spa",
      "massage",
    ],
    negativeKeywords: ["beauty supplies", "wholesale"],
    subIndustries: [
      { key: "hair", label: "Cabelo", keywords: ["hair", "hairdress"] },
      { key: "nails", label: "Unhas", keywords: ["nail", "manicure"] },
      { key: "spa", label: "Spa e massagem", keywords: ["spa", "massage"] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Serviços e valores",
      "Agendar on-line",
      "Vale-presente",
      "Horário de funcionamento",
    ],
    systemWeight: 0.6,
    systemUseCases: [
      "Agenda por profissional",
      "Pacotes e fidelidade",
      "Comissão e estoque",
    ],
  },
  {
    key: "gym",
    label: "Academias e estúdios",
    group: "Fitness",
    registryCodes: { GB: ["93130", "93110"], BR: ["9313100"] },
    keywords: [
      "gym",
      "fitness",
      "personal training",
      "crossfit",
      "pilates",
      "yoga studio",
    ],
    negativeKeywords: ["fitness equipment", "gym equipment"],
    subIndustries: [
      {
        key: "pt",
        label: "Personal trainer",
        keywords: ["personal train", "pt studio"],
      },
      {
        key: "classes",
        label: "Aulas coletivas",
        keywords: ["class", "pilates", "yoga"],
      },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Planos e valores",
      "Grade de aulas",
      "Aula experimental",
      "Estrutura",
    ],
    systemWeight: 0.7,
    systemUseCases: [
      "Alunos, planos e mensalidades",
      "Frequência e treinos",
      "Inadimplência",
    ],
  },
  {
    key: "restaurant",
    label: "Restaurantes",
    group: "Alimentação",
    registryCodes: { GB: ["56101", "56102"], BR: ["5611201"] },
    keywords: [
      "restaurant",
      "bistro",
      "dining",
      "kitchen",
      "grill",
      "trattoria",
    ],
    negativeKeywords: ["restaurant supplies", "restaurant equipment"],
    subIndustries: [
      {
        key: "fine_dining",
        label: "Alta gastronomia",
        keywords: ["fine dining", "tasting menu"],
      },
      { key: "casual", label: "Casual", keywords: ["casual", "family"] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Cardápios",
      "Reservar mesa",
      "Horário de funcionamento",
      "Eventos",
      "Como chegar",
    ],
    systemWeight: 0.5,
    systemUseCases: ["Comandas e mesas", "Estoque e ficha técnica"],
  },
  {
    key: "cafe",
    label: "Cafeterias",
    group: "Alimentação",
    registryCodes: { GB: ["56102"], BR: ["5611203"] },
    keywords: [
      "cafe",
      "café",
      "coffee shop",
      "coffee house",
      "bakery",
      "brunch",
    ],
    negativeKeywords: ["coffee wholesale", "coffee roasters supply"],
    subIndustries: [
      {
        key: "speciality_coffee",
        label: "Café especial",
        keywords: ["speciality", "roast"],
      },
    ],
    commercialWeight: 0.55,
    highTicket: false,
    bookingExpected: false,
    typicalServices: [
      "Cardápio",
      "Horário de funcionamento",
      "Como chegar",
      "Eventos e locação",
    ],
    systemWeight: 0.35,
    systemUseCases: ["Vendas e estoque básico"],
  },
  {
    key: "takeaway",
    label: "Delivery e lanchonetes",
    group: "Alimentação",
    registryCodes: { GB: ["56103"], BR: ["5620104", "5612100"] },
    keywords: [
      "takeaway",
      "take away",
      "fish and chips",
      "pizzeria",
      "kebab",
      "delivery",
    ],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "delivery",
        label: "Delivery",
        keywords: ["delivery", "deliveroo", "just eat"],
      },
    ],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Cardápio",
      "Pedir on-line",
      "Área de entrega",
      "Horário de funcionamento",
    ],
    systemWeight: 0.45,
    systemUseCases: ["Pedidos e entregas", "Cardápio e estoque"],
  },
  {
    key: "pub_bar",
    label: "Bares",
    group: "Alimentação",
    registryCodes: { GB: ["56302"], BR: ["5611204", "5611205"] },
    keywords: ["pub", "bar", "tavern", "inn", "taproom"],
    negativeKeywords: ["bar supplies", "barristers"],
    subIndustries: [
      {
        key: "food_led",
        label: "Bar com cozinha",
        keywords: ["gastro", "kitchen"],
      },
    ],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Programação",
      "Cardápios",
      "Reservar mesa",
      "Horário de funcionamento",
    ],
    systemWeight: 0.4,
    systemUseCases: ["Comandas", "Estoque de bebidas"],
  },
  {
    key: "veterinary",
    label: "Clínicas veterinárias",
    group: "Saúde",
    registryCodes: { GB: ["75000"], BR: ["7500100"] },
    keywords: ["veterinary", "vets", "vet practice", "animal hospital"],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "small_animal",
        label: "Pequenos animais",
        keywords: ["small animal", "pet"],
      },
    ],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: true,
    typicalServices: [
      "Cadastrar seu pet",
      "Agendar consulta",
      "Planos de saúde animal",
      "Emergência",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Prontuário do animal",
      "Vacinas e retornos",
      "Hotel e banho e tosa",
    ],
  },
  {
    key: "childcare",
    label: "Creches e educação infantil",
    group: "Educação",
    registryCodes: { GB: ["88910"], BR: ["8511200", "8512100"] },
    keywords: [
      "nursery",
      "childcare",
      "pre-school",
      "preschool",
      "day care",
      "daycare",
    ],
    negativeKeywords: ["plant nursery", "garden nursery"],
    subIndustries: [
      {
        key: "day_nursery",
        label: "Berçário e creche",
        keywords: ["day nursery"],
      },
    ],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: true,
    typicalServices: [
      "Agendar visita",
      "Mensalidades",
      "Nossas turmas",
      "Avaliações",
    ],
    systemWeight: 0.8,
    systemUseCases: [
      "Alunos, turmas e responsáveis",
      "Mensalidades e inadimplência",
      "Diário e comunicados",
    ],
  },
  {
    key: "driving_school",
    label: "Autoescolas",
    group: "Educação",
    registryCodes: { GB: ["85530"] },
    keywords: ["driving school", "driving instructor", "driving lessons"],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "intensive",
        label: "Cursos intensivos",
        keywords: ["intensive", "crash course"],
      },
    ],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Valores",
      "Agendar aulas",
      "Instrutores",
      "Índice de aprovação",
    ],
    systemWeight: 0.7,
    systemUseCases: [
      "Alunos e etapas do processo",
      "Agenda de aulas e instrutores",
      "Pagamentos",
    ],
  },
  {
    key: "photography",
    label: "Fotógrafos",
    group: "Criativo",
    registryCodes: { GB: ["74201", "74202", "74209"], BR: ["7420001"] },
    keywords: ["photography", "photographer", "photo studio"],
    negativeKeywords: ["photo printing", "camera shop"],
    subIndustries: [
      { key: "wedding", label: "Casamentos", keywords: ["wedding"] },
      {
        key: "commercial",
        label: "Fotografia comercial",
        keywords: ["commercial", "product"],
      },
    ],
    commercialWeight: 0.7,
    highTicket: true,
    bookingExpected: true,
    typicalServices: [
      "Portfólio",
      "Pacotes e valores",
      "Consultar disponibilidade",
      "Sobre",
    ],
    systemWeight: 0.6,
    systemUseCases: [
      "Ensaios agendados",
      "Entrega de galerias",
      "Contratos e pagamentos",
    ],
  },
  {
    key: "funeral",
    label: "Funerárias",
    group: "Serviços",
    registryCodes: { GB: ["96030"], BR: ["9603304", "9603399"] },
    keywords: ["funeral", "funeral director", "memorial"],
    negativeKeywords: [],
    subIndustries: [
      {
        key: "prepaid",
        label: "Planos",
        keywords: ["prepaid", "pre-paid", "funeral plan"],
      },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Nossos serviços",
      "Tabela de preços",
      "Planos",
      "Atendimento 24 horas",
    ],
    systemWeight: 0.6,
    systemUseCases: ["Atendimentos e planos", "Documentação", "Fornecedores"],
  },
  {
    key: "removals",
    label: "Mudanças e transportes",
    group: "Serviços",
    registryCodes: { GB: ["49420"], BR: ["4930204"] },
    keywords: [
      "removals",
      "removal company",
      "man and van",
      "house moves",
      "storage",
    ],
    negativeKeywords: [],
    subIndustries: [
      { key: "storage", label: "Guarda-móveis", keywords: ["storage"] },
    ],
    commercialWeight: 0.75,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Solicitar orçamento",
      "Serviços",
      "Guarda-móveis",
      "Área de atendimento",
      "Seguro",
    ],
    systemWeight: 0.75,
    systemUseCases: [
      "Orçamento por volume",
      "Agenda de mudanças",
      "Equipes e veículos",
    ],
  },
  {
    key: "architecture",
    label: "Escritórios de arquitetura",
    group: "Serviços profissionais",
    // No GB entry: this sector was never mapped to a SIC code here, and
    // inventing one so the list looks symmetrical would be worse than the gap.
    registryCodes: { BR: ["7111100", "7119703", "7119799"] },
    keywords: [
      "arquitetura",
      "arquiteto",
      "arquitetos",
      "projeto arquitetonico",
      "interiores",
    ],
    negativeKeywords: ["arquitetura de software", "arquitetura de sistemas"],
    subIndustries: [
      {
        key: "residencial",
        label: "Residencial",
        keywords: ["residencial", "casa", "apartamento"],
      },
      {
        key: "corporativo",
        label: "Corporativo",
        keywords: ["corporativo", "comercial", "escritorio"],
      },
      {
        key: "interiores",
        label: "Interiores",
        keywords: ["interiores", "design de interiores"],
      },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: [
      "Projetos",
      "Portfólio",
      "Como o trabalho funciona",
      "Orçamento",
    ],
    systemWeight: 1.0,
    systemUseCases: [
      "Ordens de serviço e etapas de projeto",
      "Aprovações e revisões com o cliente",
      "Horas lançadas por projeto e por pessoa",
      "Plantas e documentos versionados",
      "Prioridade e prazo por tarefa",
    ],
  },
  {
    key: "engineering",
    label: "Engenharia",
    group: "Serviços profissionais",
    registryCodes: { BR: ["7112000", "7119703", "7119799"] },
    keywords: [
      "engenharia",
      "engenheiro",
      "projeto estrutural",
      "laudo tecnico",
      "calculo estrutural",
    ],
    negativeKeywords: ["engenharia de software"],
    subIndustries: [
      {
        key: "estrutural",
        label: "Estrutural",
        keywords: ["estrutural", "calculo"],
      },
      { key: "eletrica", label: "Elétrica", keywords: ["eletrica", "spda"] },
      {
        key: "laudos",
        label: "Laudos e perícias",
        keywords: ["laudo", "pericia", "art"],
      },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ["Serviços", "Obras e projetos", "Laudos", "Contato"],
    systemWeight: 1.0,
    systemUseCases: [
      "Ordens de serviço e responsável técnico",
      "ARTs, laudos e documentos por obra",
      "Medição e cronograma",
      "Horas por projeto",
    ],
  },
  {
    key: "training_courses",
    label: "Cursos e treinamentos",
    group: "Educação",
    registryCodes: { BR: ["8599604", "8593700", "8541400", "8542200"] },
    keywords: [
      "curso",
      "cursos",
      "treinamento",
      "capacitacao",
      "escola tecnica",
      "idiomas",
    ],
    negativeKeywords: ["curso superior", "faculdade", "universidade"],
    subIndustries: [
      {
        key: "profissionalizante",
        label: "Profissionalizante",
        keywords: ["profissionalizante", "tecnico"],
      },
      {
        key: "idiomas",
        label: "Idiomas",
        keywords: ["idioma", "ingles", "espanhol"],
      },
      {
        key: "corporativo",
        label: "Corporativo",
        keywords: ["in company", "corporativo", "gerencial"],
      },
    ],
    commercialWeight: 0.85,
    highTicket: false,
    bookingExpected: true,
    typicalServices: [
      "Cursos",
      "Turmas e horários",
      "Matrícula",
      "Certificados",
    ],
    systemWeight: 0.9,
    systemUseCases: [
      "Alunos, turmas e presença",
      "Matrículas e mensalidades",
      "Inadimplência e cobrança",
      "Material e certificados",
      "Desempenho por aluno",
    ],
  },
];

export const INDUSTRY_BY_KEY: ReadonlyMap<string, IndustryProfile> = new Map(
  INDUSTRIES.map((i) => [i.key, i]),
);

export function getIndustry(key: string): IndustryProfile | undefined {
  return INDUSTRY_BY_KEY.get(key);
}

export function industryLabel(key: string): string {
  return INDUSTRY_BY_KEY.get(key)?.label ?? key;
}

/** All registry codes for the given industries in the given country. */
export function registryCodesFor(
  industryKeys: string[],
  countryCode: string,
): string[] {
  const codes = new Set<string>();
  for (const key of industryKeys) {
    for (const code of INDUSTRY_BY_KEY.get(key)?.registryCodes[countryCode] ??
      [])
      codes.add(code);
  }
  return [...codes].sort();
}

/** Industries usable in a country — i.e. those with codes or keywords for it. */
export function industriesForCountry(countryCode: string): IndustryProfile[] {
  return INDUSTRIES.filter(
    (i) => (i.registryCodes[countryCode] ?? []).length > 0,
  );
}

export const INDUSTRY_GROUPS: string[] = [
  ...new Set(INDUSTRIES.map((i) => i.group)),
].sort();
