import type { IndustryProfile } from './types.js';

/**
 * The industry catalogue.
 *
 * UK codes are SIC 2007, taken from the Companies House condensed SIC list
 * (https://resources.companieshouse.gov.uk/sic/). A company's SIC code is
 * self-declared at incorporation, so it is treated as strong-but-not-certain
 * evidence: `classify()` records SIC matches as HIGH confidence and keyword
 * matches as MEDIUM, and both are stored with the evidence that produced them.
 *
 * `commercialWeight` is a judgement about how much a website is worth to the
 * sector, not a claim about any individual company.
 */
export const INDUSTRIES: IndustryProfile[] = [
  {
    key: 'dental',
    label: 'Dental clinics',
    group: 'Healthcare',
    registryCodes: { GB: ['86230'] },
    keywords: ['dental', 'dentist', 'dentistry', 'orthodont', 'endodont', 'periodont'],
    negativeKeywords: ['dental supplies', 'dental laboratory', 'dental equipment', 'manufactur'],
    subIndustries: [
      { key: 'general_dentistry', label: 'General dentistry', keywords: ['dental practice', 'family dentist'] },
      { key: 'cosmetic_dentistry', label: 'Cosmetic dentistry', keywords: ['cosmetic', 'veneer', 'whitening', 'smile'] },
      { key: 'implants', label: 'Implants', keywords: ['implant'] },
      { key: 'orthodontics', label: 'Orthodontics', keywords: ['orthodont', 'invisalign', 'braces'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['General dentistry', 'Dental implants', 'Cosmetic dentistry', 'Orthodontics', 'Emergency appointments'],
  },
  {
    key: 'aesthetic_clinic',
    label: 'Aesthetic clinics',
    group: 'Healthcare',
    registryCodes: { GB: ['86900', '96020', '96040'] },
    keywords: ['aesthetic', 'aesthetics', 'skin clinic', 'botox', 'dermal filler', 'cosmetic clinic', 'medspa', 'med spa'],
    negativeKeywords: ['aesthetic design', 'aesthetic studio photography'],
    subIndustries: [
      { key: 'injectables', label: 'Injectables', keywords: ['botox', 'filler', 'toxin'] },
      { key: 'skin', label: 'Skin treatments', keywords: ['skin', 'peel', 'facial', 'microneedl'] },
      { key: 'laser', label: 'Laser treatments', keywords: ['laser', 'ipl'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Consultations', 'Injectable treatments', 'Skin treatments', 'Laser treatments', 'Aftercare'],
  },
  {
    key: 'medical_practice',
    label: 'Private medical practices',
    group: 'Healthcare',
    registryCodes: { GB: ['86210', '86220'] },
    keywords: ['clinic', 'private gp', 'medical practice', 'surgery', 'consultant'],
    negativeKeywords: ['veterinary', 'dental'],
    subIndustries: [
      { key: 'private_gp', label: 'Private GP', keywords: ['private gp', 'general practice'] },
      { key: 'specialist', label: 'Specialist practice', keywords: ['consultant', 'specialist'] },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Appointments', 'Health assessments', 'Specialist referrals', 'Fees and pricing'],
  },
  {
    key: 'physiotherapy',
    label: 'Physiotherapy clinics',
    group: 'Healthcare',
    registryCodes: { GB: ['86900'] },
    keywords: ['physio', 'physiotherapy', 'sports injury', 'osteopath', 'chiropract', 'rehabilitation'],
    negativeKeywords: [],
    subIndustries: [
      { key: 'sports', label: 'Sports injury', keywords: ['sports injury', 'sports therapy'] },
      { key: 'musculoskeletal', label: 'Musculoskeletal', keywords: ['back pain', 'msk', 'joint'] },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Initial assessment', 'Treatment plans', 'Sports injury rehab', 'Book an appointment'],
  },
  {
    key: 'legal',
    label: 'Law firms',
    group: 'Professional services',
    registryCodes: { GB: ['69101', '69102', '69109'] },
    keywords: ['solicitor', 'solicitors', 'law firm', 'legal', 'barrister', 'conveyanc'],
    negativeKeywords: ['legal high', 'legal services software'],
    subIndustries: [
      { key: 'conveyancing', label: 'Conveyancing', keywords: ['conveyanc', 'property law'] },
      { key: 'family', label: 'Family law', keywords: ['family law', 'divorce'] },
      { key: 'immigration', label: 'Immigration', keywords: ['immigration', 'visa'] },
      { key: 'personal_injury', label: 'Personal injury', keywords: ['personal injury', 'accident claim'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Practice areas', 'Fixed-fee services', 'Free initial consultation', 'Meet the team'],
  },
  {
    key: 'accounting',
    label: 'Accounting firms',
    group: 'Professional services',
    registryCodes: { GB: ['69201', '69202', '69203'] },
    keywords: ['accountant', 'accountants', 'accountancy', 'bookkeep', 'tax advis', 'chartered'],
    negativeKeywords: ['accounting software'],
    subIndustries: [
      { key: 'tax', label: 'Tax', keywords: ['tax'] },
      { key: 'bookkeeping', label: 'Bookkeeping', keywords: ['bookkeep', 'payroll'] },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Services and pricing', 'Free consultation', 'Making Tax Digital', 'Client portal'],
  },
  {
    key: 'real_estate',
    label: 'Estate and letting agents',
    group: 'Property',
    registryCodes: { GB: ['68310', '68320'] },
    keywords: ['estate agent', 'lettings', 'letting agent', 'property management', 'realtor'],
    negativeKeywords: [],
    subIndustries: [
      { key: 'sales', label: 'Sales', keywords: ['for sale', 'sales'] },
      { key: 'lettings', label: 'Lettings', keywords: ['letting', 'rental'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Free valuation', 'Properties for sale', 'Properties to let', 'Landlord services'],
  },
  {
    key: 'construction',
    label: 'Construction companies',
    group: 'Trades',
    registryCodes: { GB: ['41201', '41202', '43120', '43110', '43999'] },
    keywords: ['construction', 'builders', 'building services', 'contractors', 'renovation', 'extension', 'loft conversion'],
    negativeKeywords: ['building society', 'construction software'],
    subIndustries: [
      { key: 'extensions', label: 'Extensions and loft conversions', keywords: ['extension', 'loft conversion'] },
      { key: 'newbuild', label: 'New build', keywords: ['new build', 'development'] },
      { key: 'refurbishment', label: 'Refurbishment', keywords: ['refurbish', 'renovation'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Recent projects', 'Free quotation', 'Accreditations', 'Areas covered'],
  },
  {
    key: 'roofing',
    label: 'Roofing companies',
    group: 'Trades',
    registryCodes: { GB: ['43910'] },
    keywords: ['roofing', 'roofer', 'roofs', 'flat roof', 'guttering'],
    negativeKeywords: ['roofing supplies', 'roofing wholesale'],
    subIndustries: [
      { key: 'flat_roofing', label: 'Flat roofing', keywords: ['flat roof', 'epdm', 'grp'] },
      { key: 'pitched_roofing', label: 'Pitched roofing', keywords: ['tile', 'slate', 'pitched'] },
    ],
    commercialWeight: 0.95,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Roof repairs', 'New roofs', 'Emergency call-out', 'Free survey', 'Guarantees'],
  },
  {
    key: 'plumbing',
    label: 'Plumbing companies',
    group: 'Trades',
    registryCodes: { GB: ['43220'] },
    keywords: ['plumbing', 'plumber', 'bathroom installation', 'drainage'],
    negativeKeywords: ['plumbing supplies', 'plumbing merchants', 'wholesale'],
    subIndustries: [
      { key: 'emergency', label: 'Emergency plumbing', keywords: ['emergency', '24 hour', '24/7'] },
      { key: 'bathrooms', label: 'Bathroom installation', keywords: ['bathroom'] },
    ],
    commercialWeight: 0.9,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Emergency call-out', 'Bathroom installation', 'Leak repairs', 'Areas covered'],
  },
  {
    key: 'heating_hvac',
    label: 'Heating and HVAC companies',
    group: 'Trades',
    registryCodes: { GB: ['43220'] },
    keywords: ['heating', 'boiler', 'hvac', 'air conditioning', 'gas safe', 'heat pump', 'underfloor heating'],
    negativeKeywords: ['heating supplies', 'wholesale'],
    subIndustries: [
      { key: 'boilers', label: 'Boiler installation', keywords: ['boiler'] },
      { key: 'heat_pumps', label: 'Heat pumps', keywords: ['heat pump', 'air source', 'ground source'] },
      { key: 'air_conditioning', label: 'Air conditioning', keywords: ['air conditioning', 'aircon'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Boiler installation', 'Servicing and repairs', 'Free quote', 'Finance options', 'Accreditations'],
  },
  {
    key: 'electrician',
    label: 'Electricians',
    group: 'Trades',
    registryCodes: { GB: ['43210'] },
    keywords: ['electrical', 'electrician', 'electrics', 'rewire', 'ev charger'],
    negativeKeywords: ['electrical wholesale', 'electrical manufacturing'],
    subIndustries: [
      { key: 'domestic', label: 'Domestic electrical', keywords: ['domestic', 'rewire'] },
      { key: 'ev_charging', label: 'EV charging', keywords: ['ev charger', 'electric vehicle'] },
    ],
    commercialWeight: 0.9,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Domestic electrical work', 'EICR and certificates', 'EV charger installation', 'Emergency call-out'],
  },
  {
    key: 'joinery',
    label: 'Joinery and carpentry',
    group: 'Trades',
    registryCodes: { GB: ['43320'] },
    keywords: ['joinery', 'carpenter', 'carpentry', 'bespoke furniture', 'fitted wardrobes', 'kitchen fitting'],
    negativeKeywords: [],
    subIndustries: [{ key: 'bespoke', label: 'Bespoke joinery', keywords: ['bespoke', 'made to measure'] }],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Bespoke joinery', 'Fitted kitchens and wardrobes', 'Project gallery', 'Free design visit'],
  },
  {
    key: 'plastering_decorating',
    label: 'Plastering and decorating',
    group: 'Trades',
    registryCodes: { GB: ['43310', '43341', '43342', '43330'] },
    keywords: ['plastering', 'plasterer', 'decorator', 'painting and decorating', 'rendering', 'glazing', 'flooring'],
    negativeKeywords: [],
    subIndustries: [
      { key: 'plastering', label: 'Plastering', keywords: ['plaster', 'render'] },
      { key: 'decorating', label: 'Painting and decorating', keywords: ['decorat', 'painting'] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Services', 'Recent work gallery', 'Free quote', 'Areas covered'],
  },
  {
    key: 'landscaping',
    label: 'Landscaping and gardening',
    group: 'Trades',
    registryCodes: { GB: ['81300'] },
    keywords: ['landscap', 'garden', 'groundwork', 'driveway', 'paving', 'tree surgeon'],
    negativeKeywords: ['garden centre'],
    subIndustries: [
      { key: 'design', label: 'Garden design', keywords: ['design'] },
      { key: 'driveways', label: 'Driveways and paving', keywords: ['driveway', 'paving', 'patio'] },
    ],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Garden design', 'Driveways and patios', 'Project gallery', 'Free site visit'],
  },
  {
    key: 'cleaning',
    label: 'Cleaning companies',
    group: 'Services',
    registryCodes: { GB: ['81210', '81221', '81222', '81229', '81299'] },
    keywords: ['cleaning', 'cleaners', 'domestic cleaning', 'commercial cleaning', 'end of tenancy'],
    negativeKeywords: ['dry cleaning', 'cleaning products', 'cleaning supplies'],
    subIndustries: [
      { key: 'commercial', label: 'Commercial cleaning', keywords: ['commercial', 'office cleaning'] },
      { key: 'domestic', label: 'Domestic cleaning', keywords: ['domestic', 'house cleaning'] },
      { key: 'end_of_tenancy', label: 'End of tenancy', keywords: ['end of tenancy', 'move out'] },
    ],
    commercialWeight: 0.75,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Services and pricing', 'Instant quote', 'Areas covered', 'Insurance and vetting'],
  },
  {
    key: 'auto_repair',
    label: 'Auto repair and garages',
    group: 'Automotive',
    registryCodes: { GB: ['45200'] },
    keywords: ['garage', 'mot', 'car repair', 'servicing', 'bodyshop', 'tyres'],
    negativeKeywords: ['garage doors', 'car sales'],
    subIndustries: [
      { key: 'mot_servicing', label: 'MOT and servicing', keywords: ['mot', 'service'] },
      { key: 'bodywork', label: 'Bodywork', keywords: ['bodyshop', 'body repair'] },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Book an MOT', 'Servicing', 'Repairs', 'Prices', 'Find us'],
  },
  {
    key: 'barber',
    label: 'Barbers',
    group: 'Personal care',
    registryCodes: { GB: ['96020'] },
    keywords: ['barber', 'barbers', 'barbershop', 'grooming'],
    negativeKeywords: [],
    subIndustries: [{ key: 'traditional', label: 'Traditional barbering', keywords: ['traditional', 'hot towel'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Price list', 'Book online', 'Opening hours', 'Find us'],
  },
  {
    key: 'beauty_salon',
    label: 'Beauty salons',
    group: 'Personal care',
    registryCodes: { GB: ['96020', '96040'] },
    keywords: ['salon', 'beauty', 'hairdress', 'nails', 'lashes', 'spa', 'massage'],
    negativeKeywords: ['beauty supplies', 'wholesale'],
    subIndustries: [
      { key: 'hair', label: 'Hair', keywords: ['hair', 'hairdress'] },
      { key: 'nails', label: 'Nails', keywords: ['nail', 'manicure'] },
      { key: 'spa', label: 'Spa and massage', keywords: ['spa', 'massage'] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Treatments and prices', 'Book online', 'Gift vouchers', 'Opening hours'],
  },
  {
    key: 'gym',
    label: 'Gyms and fitness studios',
    group: 'Fitness',
    registryCodes: { GB: ['93130', '93110'] },
    keywords: ['gym', 'fitness', 'personal training', 'crossfit', 'pilates', 'yoga studio'],
    negativeKeywords: ['fitness equipment', 'gym equipment'],
    subIndustries: [
      { key: 'pt', label: 'Personal training', keywords: ['personal train', 'pt studio'] },
      { key: 'classes', label: 'Classes', keywords: ['class', 'pilates', 'yoga'] },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Memberships and pricing', 'Class timetable', 'Free trial', 'Facilities'],
  },
  {
    key: 'restaurant',
    label: 'Restaurants',
    group: 'Hospitality',
    registryCodes: { GB: ['56101', '56102'] },
    keywords: ['restaurant', 'bistro', 'dining', 'kitchen', 'grill', 'trattoria'],
    negativeKeywords: ['restaurant supplies', 'restaurant equipment'],
    subIndustries: [
      { key: 'fine_dining', label: 'Fine dining', keywords: ['fine dining', 'tasting menu'] },
      { key: 'casual', label: 'Casual dining', keywords: ['casual', 'family'] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Menus', 'Book a table', 'Opening hours', 'Private dining', 'Find us'],
  },
  {
    key: 'cafe',
    label: 'Cafés',
    group: 'Hospitality',
    registryCodes: { GB: ['56102'] },
    keywords: ['cafe', 'café', 'coffee shop', 'coffee house', 'bakery', 'brunch'],
    negativeKeywords: ['coffee wholesale', 'coffee roasters supply'],
    subIndustries: [{ key: 'speciality_coffee', label: 'Speciality coffee', keywords: ['speciality', 'roast'] }],
    commercialWeight: 0.55,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Menu', 'Opening hours', 'Find us', 'Events and private hire'],
  },
  {
    key: 'takeaway',
    label: 'Takeaways',
    group: 'Hospitality',
    registryCodes: { GB: ['56103'] },
    keywords: ['takeaway', 'take away', 'fish and chips', 'pizzeria', 'kebab', 'delivery'],
    negativeKeywords: [],
    subIndustries: [{ key: 'delivery', label: 'Delivery', keywords: ['delivery', 'deliveroo', 'just eat'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Menu', 'Order online', 'Delivery area', 'Opening hours'],
  },
  {
    key: 'pub_bar',
    label: 'Pubs and bars',
    group: 'Hospitality',
    registryCodes: { GB: ['56302'] },
    keywords: ['pub', 'bar', 'tavern', 'inn', 'taproom'],
    negativeKeywords: ['bar supplies', 'barristers'],
    subIndustries: [{ key: 'food_led', label: 'Food-led pub', keywords: ['gastro', 'kitchen'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Whats on', 'Menus', 'Book a table', 'Opening hours'],
  },
  {
    key: 'veterinary',
    label: 'Veterinary practices',
    group: 'Healthcare',
    registryCodes: { GB: ['75000'] },
    keywords: ['veterinary', 'vets', 'vet practice', 'animal hospital'],
    negativeKeywords: [],
    subIndustries: [{ key: 'small_animal', label: 'Small animal', keywords: ['small animal', 'pet'] }],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Register your pet', 'Book an appointment', 'Health plans', 'Emergency care'],
  },
  {
    key: 'childcare',
    label: 'Nurseries and childcare',
    group: 'Education',
    registryCodes: { GB: ['88910'] },
    keywords: ['nursery', 'childcare', 'pre-school', 'preschool', 'day care', 'daycare'],
    negativeKeywords: ['plant nursery', 'garden nursery'],
    subIndustries: [{ key: 'day_nursery', label: 'Day nursery', keywords: ['day nursery'] }],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Book a visit', 'Fees and funding', 'Our rooms', 'Ofsted rating'],
  },
  {
    key: 'driving_school',
    label: 'Driving schools',
    group: 'Education',
    registryCodes: { GB: ['85530'] },
    keywords: ['driving school', 'driving instructor', 'driving lessons'],
    negativeKeywords: [],
    subIndustries: [{ key: 'intensive', label: 'Intensive courses', keywords: ['intensive', 'crash course'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Prices', 'Book lessons', 'Instructors', 'Pass rates'],
  },
  {
    key: 'photography',
    label: 'Photographers',
    group: 'Creative',
    registryCodes: { GB: ['74201', '74202', '74209'] },
    keywords: ['photography', 'photographer', 'photo studio'],
    negativeKeywords: ['photo printing', 'camera shop'],
    subIndustries: [
      { key: 'wedding', label: 'Wedding photography', keywords: ['wedding'] },
      { key: 'commercial', label: 'Commercial photography', keywords: ['commercial', 'product'] },
    ],
    commercialWeight: 0.7,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Portfolio', 'Packages and pricing', 'Check availability', 'About'],
  },
  {
    key: 'funeral',
    label: 'Funeral directors',
    group: 'Services',
    registryCodes: { GB: ['96030'] },
    keywords: ['funeral', 'funeral director', 'memorial'],
    negativeKeywords: [],
    subIndustries: [{ key: 'prepaid', label: 'Prepaid plans', keywords: ['prepaid', 'pre-paid', 'funeral plan'] }],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Our services', 'Prices (Standardised Price List)', 'Prepaid plans', '24-hour contact'],
  },
  {
    key: 'removals',
    label: 'Removals companies',
    group: 'Services',
    registryCodes: { GB: ['49420'] },
    keywords: ['removals', 'removal company', 'man and van', 'house moves', 'storage'],
    negativeKeywords: [],
    subIndustries: [{ key: 'storage', label: 'Storage', keywords: ['storage'] }],
    commercialWeight: 0.75,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Get a quote', 'Services', 'Storage', 'Areas covered', 'Insurance'],
  },
];

export const INDUSTRY_BY_KEY: ReadonlyMap<string, IndustryProfile> = new Map(
  INDUSTRIES.map((i) => [i.key, i]),
);

export function getIndustry(key: string): IndustryProfile | undefined {
  return INDUSTRY_BY_KEY.get(key);
}

export function industryLabel(key: string): string {
  return INDUSTRY_BY_KEY.get(key)?.label ?? key;
}

/** All registry codes for the given industries in the given country. */
export function registryCodesFor(industryKeys: string[], countryCode: string): string[] {
  const codes = new Set<string>();
  for (const key of industryKeys) {
    for (const code of INDUSTRY_BY_KEY.get(key)?.registryCodes[countryCode] ?? []) codes.add(code);
  }
  return [...codes].sort();
}

/** Industries usable in a country — i.e. those with codes or keywords for it. */
export function industriesForCountry(countryCode: string): IndustryProfile[] {
  return INDUSTRIES.filter((i) => (i.registryCodes[countryCode] ?? []).length > 0);
}

export const INDUSTRY_GROUPS: string[] = [...new Set(INDUSTRIES.map((i) => i.group))].sort();
