import type { IndustryProfile } from './types.js';

/**
 * The industry catalogue.
 *
 * UK codes are SIC 2007, taken from the Companies House condensed SIC list
 * (https://resources.companieshouse.gov.uk/sic/). A company's SIC code is
 * self-declared at incorporation, so it is treated as strong-but-not-certain
 * evidence: `classify()` records SIC matches as HIGH confidence and keyword
 * matches as MEDIUM, and both are stored with the evidence that produced them.
 *
 * `commercialWeight` is a judgement about how much a website is worth to the
 * sector, not a claim about any individual company.
 */
export const INDUSTRIES: IndustryProfile[] = [
  {
    key: 'dental',
    label: 'Dental clinics',
    group: 'Healthcare',
    registryCodes: { GB: ['86230'], BR: ['8630504'] },
    keywords: ['dental', 'dentist', 'dentistry', 'orthodont', 'endodont', 'periodont'],
    negativeKeywords: ['dental supplies', 'dental laboratory', 'dental equipment', 'manufactur'],
    subIndustries: [
      { key: 'general_dentistry', label: 'General dentistry', keywords: ['dental practice', 'family dentist'] },
      { key: 'cosmetic_dentistry', label: 'Cosmetic dentistry', keywords: ['cosmetic', 'veneer', 'whitening', 'smile'] },
      { key: 'implants', label: 'Implants', keywords: ['implant'] },
      { key: 'orthodontics', label: 'Orthodontics', keywords: ['orthodont', 'invisalign', 'braces'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['General dentistry', 'Dental implants', 'Cosmetic dentistry', 'Orthodontics', 'Emergency appointments'],
    systemWeight: 0.8,
    systemUseCases: ['Prontuário e histórico do paciente', 'Agenda por profissional e sala', 'Orçamentos e planos de tratamento', 'Convênios e repasses'],
  },
  {
    key: 'aesthetic_clinic',
    label: 'Aesthetic clinics',
    group: 'Healthcare',
    registryCodes: { GB: ['86900', '96020', '96040'], BR: ['9602502'] },
    keywords: ['aesthetic', 'aesthetics', 'skin clinic', 'botox', 'dermal filler', 'cosmetic clinic', 'medspa', 'med spa'],
    negativeKeywords: ['aesthetic design', 'aesthetic studio photography'],
    subIndustries: [
      { key: 'injectables', label: 'Injectables', keywords: ['botox', 'filler', 'toxin'] },
      { key: 'skin', label: 'Skin treatments', keywords: ['skin', 'peel', 'facial', 'microneedl'] },
      { key: 'laser', label: 'Laser treatments', keywords: ['laser', 'ipl'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Consultations', 'Injectable treatments', 'Skin treatments', 'Laser treatments', 'Aftercare'],
    systemWeight: 0.75,
    systemUseCases: ['Ficha de anamnese e evolução', 'Agenda e pacotes de sessões', 'Estoque de insumos', 'Comissão por profissional'],
  },
  {
    key: 'medical_practice',
    label: 'Private medical practices',
    group: 'Healthcare',
    registryCodes: { GB: ['86210', '86220'], BR: ['8630501', '8630502', '8630503'] },
    keywords: ['clinic', 'private gp', 'medical practice', 'surgery', 'consultant'],
    negativeKeywords: ['veterinary', 'dental'],
    subIndustries: [
      { key: 'private_gp', label: 'Private GP', keywords: ['private gp', 'general practice'] },
      { key: 'specialist', label: 'Specialist practice', keywords: ['consultant', 'specialist'] },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Appointments', 'Health assessments', 'Specialist referrals', 'Fees and pricing'],
    systemWeight: 0.8,
    systemUseCases: ['Prontuário eletrônico', 'Agenda e confirmação de consulta', 'Faturamento de convênios'],
  },
  {
    key: 'physiotherapy',
    label: 'Physiotherapy clinics',
    group: 'Healthcare',
    registryCodes: { GB: ['86900'], BR: ['8650004', '8650003'] },
    keywords: ['physio', 'physiotherapy', 'sports injury', 'osteopath', 'chiropract', 'rehabilitation'],
    negativeKeywords: [],
    subIndustries: [
      { key: 'sports', label: 'Sports injury', keywords: ['sports injury', 'sports therapy'] },
      { key: 'musculoskeletal', label: 'Musculoskeletal', keywords: ['back pain', 'msk', 'joint'] },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Initial assessment', 'Treatment plans', 'Sports injury rehab', 'Book an appointment'],
    systemWeight: 0.75,
    systemUseCases: ['Evolução por sessão', 'Pacotes e frequência', 'Agenda por profissional'],
  },
  {
    key: 'legal',
    label: 'Law firms',
    group: 'Professional services',
    registryCodes: { GB: ['69101', '69102', '69109'], BR: ['6911701'] },
    keywords: ['solicitor', 'solicitors', 'law firm', 'legal', 'barrister', 'conveyanc'],
    negativeKeywords: ['legal high', 'legal services software'],
    subIndustries: [
      { key: 'conveyancing', label: 'Conveyancing', keywords: ['conveyanc', 'property law'] },
      { key: 'family', label: 'Family law', keywords: ['family law', 'divorce'] },
      { key: 'immigration', label: 'Immigration', keywords: ['immigration', 'visa'] },
      { key: 'personal_injury', label: 'Personal injury', keywords: ['personal injury', 'accident claim'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Practice areas', 'Fixed-fee services', 'Free initial consultation', 'Meet the team'],
    systemWeight: 0.9,
    systemUseCases: ['Processos, prazos e andamentos', 'Documentos por cliente', 'Horas e honorários', 'Agenda de audiências'],
  },
  {
    key: 'accounting',
    label: 'Accounting firms',
    group: 'Professional services',
    registryCodes: { GB: ['69201', '69202', '69203'], BR: ['6920601'] },
    keywords: ['accountant', 'accountants', 'accountancy', 'bookkeep', 'tax advis', 'chartered'],
    negativeKeywords: ['accounting software'],
    subIndustries: [
      { key: 'tax', label: 'Tax', keywords: ['tax'] },
      { key: 'bookkeeping', label: 'Bookkeeping', keywords: ['bookkeep', 'payroll'] },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Services and pricing', 'Free consultation', 'Making Tax Digital', 'Client portal'],
    systemWeight: 0.9,
    systemUseCases: ['Obrigações por cliente e vencimento', 'Documentos recebidos', 'Honorários recorrentes'],
  },
  {
    key: 'real_estate',
    label: 'Estate and letting agents',
    group: 'Property',
    registryCodes: { GB: ['68310', '68320'], BR: ['6821801', '6821802', '6822600'] },
    keywords: ['estate agent', 'lettings', 'letting agent', 'property management', 'realtor'],
    negativeKeywords: [],
    subIndustries: [
      { key: 'sales', label: 'Sales', keywords: ['for sale', 'sales'] },
      { key: 'lettings', label: 'Lettings', keywords: ['letting', 'rental'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Free valuation', 'Properties for sale', 'Properties to let', 'Landlord services'],
    systemWeight: 0.85,
    systemUseCases: ['Carteira de imóveis e fotos', 'Visitas agendadas', 'Propostas e contratos', 'Repasse de aluguel'],
  },
  {
    key: 'construction',
    label: 'Construction companies',
    group: 'Trades',
    registryCodes: { GB: ['41201', '41202', '43120', '43110', '43999'], BR: ['4120400', '4399101', '4399103', '4399199', '4299599'] },
    keywords: ['construction', 'builders', 'building services', 'contractors', 'renovation', 'extension', 'loft conversion'],
    negativeKeywords: ['building society', 'construction software'],
    subIndustries: [
      { key: 'extensions', label: 'Extensions and loft conversions', keywords: ['extension', 'loft conversion'] },
      { key: 'newbuild', label: 'New build', keywords: ['new build', 'development'] },
      { key: 'refurbishment', label: 'Refurbishment', keywords: ['refurbish', 'renovation'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Recent projects', 'Free quotation', 'Accreditations', 'Areas covered'],
    systemWeight: 0.95,
    systemUseCases: ['Ordens de serviço e etapas', 'Medição e diário de obra', 'Orçamento x realizado', 'Equipes e alocação'],
  },
  {
    key: 'roofing',
    label: 'Roofing companies',
    group: 'Trades',
    registryCodes: { GB: ['43910'] },
    keywords: ['roofing', 'roofer', 'roofs', 'flat roof', 'guttering'],
    negativeKeywords: ['roofing supplies', 'roofing wholesale'],
    subIndustries: [
      { key: 'flat_roofing', label: 'Flat roofing', keywords: ['flat roof', 'epdm', 'grp'] },
      { key: 'pitched_roofing', label: 'Pitched roofing', keywords: ['tile', 'slate', 'pitched'] },
    ],
    commercialWeight: 0.95,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Roof repairs', 'New roofs', 'Emergency call-out', 'Free survey', 'Guarantees'],
    systemWeight: 0.8,
    systemUseCases: ['Ordens de serviço', 'Orçamento e visita técnica', 'Garantias'],
  },
  {
    key: 'plumbing',
    label: 'Plumbing companies',
    group: 'Trades',
    registryCodes: { GB: ['43220'], BR: ['4322301'] },
    keywords: ['plumbing', 'plumber', 'bathroom installation', 'drainage'],
    negativeKeywords: ['plumbing supplies', 'plumbing merchants', 'wholesale'],
    subIndustries: [
      { key: 'emergency', label: 'Emergency plumbing', keywords: ['emergency', '24 hour', '24/7'] },
      { key: 'bathrooms', label: 'Bathroom installation', keywords: ['bathroom'] },
    ],
    commercialWeight: 0.9,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Emergency call-out', 'Bathroom installation', 'Leak repairs', 'Areas covered'],
    systemWeight: 0.8,
    systemUseCases: ['Ordens de serviço e urgências', 'Roteiro das equipes', 'Orçamento no local'],
  },
  {
    key: 'heating_hvac',
    label: 'Heating and HVAC companies',
    group: 'Trades',
    registryCodes: { GB: ['43220'], BR: ['4322302'] },
    keywords: ['heating', 'boiler', 'hvac', 'air conditioning', 'gas safe', 'heat pump', 'underfloor heating'],
    negativeKeywords: ['heating supplies', 'wholesale'],
    subIndustries: [
      { key: 'boilers', label: 'Boiler installation', keywords: ['boiler'] },
      { key: 'heat_pumps', label: 'Heat pumps', keywords: ['heat pump', 'air source', 'ground source'] },
      { key: 'air_conditioning', label: 'Air conditioning', keywords: ['air conditioning', 'aircon'] },
    ],
    commercialWeight: 1.0,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Boiler installation', 'Servicing and repairs', 'Free quote', 'Finance options', 'Accreditations'],
    systemWeight: 0.85,
    systemUseCases: ['Ordens de serviço e manutenção preventiva', 'Contratos por equipamento', 'Histórico por cliente'],
  },
  {
    key: 'electrician',
    label: 'Electricians',
    group: 'Trades',
    registryCodes: { GB: ['43210'], BR: ['4321500'] },
    keywords: ['electrical', 'electrician', 'electrics', 'rewire', 'ev charger'],
    negativeKeywords: ['electrical wholesale', 'electrical manufacturing'],
    subIndustries: [
      { key: 'domestic', label: 'Domestic electrical', keywords: ['domestic', 'rewire'] },
      { key: 'ev_charging', label: 'EV charging', keywords: ['ev charger', 'electric vehicle'] },
    ],
    commercialWeight: 0.9,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Domestic electrical work', 'EICR and certificates', 'EV charger installation', 'Emergency call-out'],
    systemWeight: 0.8,
    systemUseCases: ['Ordens de serviço', 'Laudos e certificados', 'Roteiro das equipes'],
  },
  {
    key: 'joinery',
    label: 'Joinery and carpentry',
    group: 'Trades',
    registryCodes: { GB: ['43320'], BR: ['4330402', '3101200'] },
    keywords: ['joinery', 'carpenter', 'carpentry', 'bespoke furniture', 'fitted wardrobes', 'kitchen fitting'],
    negativeKeywords: [],
    subIndustries: [{ key: 'bespoke', label: 'Bespoke joinery', keywords: ['bespoke', 'made to measure'] }],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Bespoke joinery', 'Fitted kitchens and wardrobes', 'Project gallery', 'Free design visit'],
    systemWeight: 0.75,
    systemUseCases: ['Projeto e medição', 'Etapas de produção', 'Entrega e montagem'],
  },
  {
    key: 'plastering_decorating',
    label: 'Plastering and decorating',
    group: 'Trades',
    registryCodes: { GB: ['43310', '43341', '43342', '43330'], BR: ['4330404', '4399103'] },
    keywords: ['plastering', 'plasterer', 'decorator', 'painting and decorating', 'rendering', 'glazing', 'flooring'],
    negativeKeywords: [],
    subIndustries: [
      { key: 'plastering', label: 'Plastering', keywords: ['plaster', 'render'] },
      { key: 'decorating', label: 'Painting and decorating', keywords: ['decorat', 'painting'] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Services', 'Recent work gallery', 'Free quote', 'Areas covered'],
    systemWeight: 0.6,
    systemUseCases: ['Ordens de serviço', 'Orçamento por metragem'],
  },
  {
    key: 'landscaping',
    label: 'Landscaping and gardening',
    group: 'Trades',
    registryCodes: { GB: ['81300'] },
    keywords: ['landscap', 'garden', 'groundwork', 'driveway', 'paving', 'tree surgeon'],
    negativeKeywords: ['garden centre'],
    subIndustries: [
      { key: 'design', label: 'Garden design', keywords: ['design'] },
      { key: 'driveways', label: 'Driveways and paving', keywords: ['driveway', 'paving', 'patio'] },
    ],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Garden design', 'Driveways and patios', 'Project gallery', 'Free site visit'],
    systemWeight: 0.7,
    systemUseCases: ['Ordens de serviço e rotas', 'Contratos de manutenção'],
  },
  {
    key: 'cleaning',
    label: 'Cleaning companies',
    group: 'Services',
    registryCodes: { GB: ['81210', '81221', '81222', '81229', '81299'], BR: ['8121400'] },
    keywords: ['cleaning', 'cleaners', 'domestic cleaning', 'commercial cleaning', 'end of tenancy'],
    negativeKeywords: ['dry cleaning', 'cleaning products', 'cleaning supplies'],
    subIndustries: [
      { key: 'commercial', label: 'Commercial cleaning', keywords: ['commercial', 'office cleaning'] },
      { key: 'domestic', label: 'Domestic cleaning', keywords: ['domestic', 'house cleaning'] },
      { key: 'end_of_tenancy', label: 'End of tenancy', keywords: ['end of tenancy', 'move out'] },
    ],
    commercialWeight: 0.75,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Services and pricing', 'Instant quote', 'Areas covered', 'Insurance and vetting'],
    systemWeight: 0.8,
    systemUseCases: ['Escala de equipes e rotas', 'Contratos e postos', 'Checklist por posto'],
  },
  {
    key: 'auto_repair',
    label: 'Auto repair and garages',
    group: 'Automotive',
    registryCodes: { GB: ['45200'], BR: ['4520001', '4520002'] },
    keywords: ['garage', 'mot', 'car repair', 'servicing', 'bodyshop', 'tyres'],
    negativeKeywords: ['garage doors', 'car sales'],
    subIndustries: [
      { key: 'mot_servicing', label: 'MOT and servicing', keywords: ['mot', 'service'] },
      { key: 'bodywork', label: 'Bodywork', keywords: ['bodyshop', 'body repair'] },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Book an MOT', 'Servicing', 'Repairs', 'Prices', 'Find us'],
    systemWeight: 0.8,
    systemUseCases: ['Ordem de serviço e orçamento', 'Peças e estoque', 'Histórico por veículo'],
  },
  {
    key: 'barber',
    label: 'Barbers',
    group: 'Personal care',
    registryCodes: { GB: ['96020'], BR: ['9602501'] },
    keywords: ['barber', 'barbers', 'barbershop', 'grooming'],
    negativeKeywords: [],
    subIndustries: [{ key: 'traditional', label: 'Traditional barbering', keywords: ['traditional', 'hot towel'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Price list', 'Book online', 'Opening hours', 'Find us'],
    systemWeight: 0.45,
    systemUseCases: ['Agenda online', 'Comissão por profissional'],
  },
  {
    key: 'beauty_salon',
    label: 'Beauty salons',
    group: 'Personal care',
    registryCodes: { GB: ['96020', '96040'], BR: ['9602501', '9602502'] },
    keywords: ['salon', 'beauty', 'hairdress', 'nails', 'lashes', 'spa', 'massage'],
    negativeKeywords: ['beauty supplies', 'wholesale'],
    subIndustries: [
      { key: 'hair', label: 'Hair', keywords: ['hair', 'hairdress'] },
      { key: 'nails', label: 'Nails', keywords: ['nail', 'manicure'] },
      { key: 'spa', label: 'Spa and massage', keywords: ['spa', 'massage'] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Treatments and prices', 'Book online', 'Gift vouchers', 'Opening hours'],
    systemWeight: 0.6,
    systemUseCases: ['Agenda por profissional', 'Pacotes e fidelidade', 'Comissão e estoque'],
  },
  {
    key: 'gym',
    label: 'Gyms and fitness studios',
    group: 'Fitness',
    registryCodes: { GB: ['93130', '93110'], BR: ['9313100'] },
    keywords: ['gym', 'fitness', 'personal training', 'crossfit', 'pilates', 'yoga studio'],
    negativeKeywords: ['fitness equipment', 'gym equipment'],
    subIndustries: [
      { key: 'pt', label: 'Personal training', keywords: ['personal train', 'pt studio'] },
      { key: 'classes', label: 'Classes', keywords: ['class', 'pilates', 'yoga'] },
    ],
    commercialWeight: 0.8,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Memberships and pricing', 'Class timetable', 'Free trial', 'Facilities'],
    systemWeight: 0.7,
    systemUseCases: ['Alunos, planos e mensalidades', 'Frequência e treinos', 'Inadimplência'],
  },
  {
    key: 'restaurant',
    label: 'Restaurants',
    group: 'Hospitality',
    registryCodes: { GB: ['56101', '56102'], BR: ['5611201'] },
    keywords: ['restaurant', 'bistro', 'dining', 'kitchen', 'grill', 'trattoria'],
    negativeKeywords: ['restaurant supplies', 'restaurant equipment'],
    subIndustries: [
      { key: 'fine_dining', label: 'Fine dining', keywords: ['fine dining', 'tasting menu'] },
      { key: 'casual', label: 'Casual dining', keywords: ['casual', 'family'] },
    ],
    commercialWeight: 0.7,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Menus', 'Book a table', 'Opening hours', 'Private dining', 'Find us'],
    systemWeight: 0.5,
    systemUseCases: ['Comandas e mesas', 'Estoque e ficha técnica'],
  },
  {
    key: 'cafe',
    label: 'Cafés',
    group: 'Hospitality',
    registryCodes: { GB: ['56102'], BR: ['5611203'] },
    keywords: ['cafe', 'café', 'coffee shop', 'coffee house', 'bakery', 'brunch'],
    negativeKeywords: ['coffee wholesale', 'coffee roasters supply'],
    subIndustries: [{ key: 'speciality_coffee', label: 'Speciality coffee', keywords: ['speciality', 'roast'] }],
    commercialWeight: 0.55,
    highTicket: false,
    bookingExpected: false,
    typicalServices: ['Menu', 'Opening hours', 'Find us', 'Events and private hire'],
    systemWeight: 0.35,
    systemUseCases: ['Vendas e estoque básico'],
  },
  {
    key: 'takeaway',
    label: 'Takeaways',
    group: 'Hospitality',
    registryCodes: { GB: ['56103'], BR: ['5620104', '5612100'] },
    keywords: ['takeaway', 'take away', 'fish and chips', 'pizzeria', 'kebab', 'delivery'],
    negativeKeywords: [],
    subIndustries: [{ key: 'delivery', label: 'Delivery', keywords: ['delivery', 'deliveroo', 'just eat'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Menu', 'Order online', 'Delivery area', 'Opening hours'],
    systemWeight: 0.45,
    systemUseCases: ['Pedidos e entregas', 'Cardápio e estoque'],
  },
  {
    key: 'pub_bar',
    label: 'Pubs and bars',
    group: 'Hospitality',
    registryCodes: { GB: ['56302'], BR: ['5611204', '5611205'] },
    keywords: ['pub', 'bar', 'tavern', 'inn', 'taproom'],
    negativeKeywords: ['bar supplies', 'barristers'],
    subIndustries: [{ key: 'food_led', label: 'Food-led pub', keywords: ['gastro', 'kitchen'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Whats on', 'Menus', 'Book a table', 'Opening hours'],
    systemWeight: 0.4,
    systemUseCases: ['Comandas', 'Estoque de bebidas'],
  },
  {
    key: 'veterinary',
    label: 'Veterinary practices',
    group: 'Healthcare',
    registryCodes: { GB: ['75000'], BR: ['7500100'] },
    keywords: ['veterinary', 'vets', 'vet practice', 'animal hospital'],
    negativeKeywords: [],
    subIndustries: [{ key: 'small_animal', label: 'Small animal', keywords: ['small animal', 'pet'] }],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Register your pet', 'Book an appointment', 'Health plans', 'Emergency care'],
    systemWeight: 0.8,
    systemUseCases: ['Prontuário do animal', 'Vacinas e retornos', 'Internação e banho e tosa'],
  },
  {
    key: 'childcare',
    label: 'Nurseries and childcare',
    group: 'Education',
    registryCodes: { GB: ['88910'], BR: ['8511200', '8512100'] },
    keywords: ['nursery', 'childcare', 'pre-school', 'preschool', 'day care', 'daycare'],
    negativeKeywords: ['plant nursery', 'garden nursery'],
    subIndustries: [{ key: 'day_nursery', label: 'Day nursery', keywords: ['day nursery'] }],
    commercialWeight: 0.85,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Book a visit', 'Fees and funding', 'Our rooms', 'Ofsted rating'],
    systemWeight: 0.8,
    systemUseCases: ['Alunos, turmas e responsáveis', 'Mensalidades e inadimplência', 'Diário e comunicados'],
  },
  {
    key: 'driving_school',
    label: 'Driving schools',
    group: 'Education',
    registryCodes: { GB: ['85530'] },
    keywords: ['driving school', 'driving instructor', 'driving lessons'],
    negativeKeywords: [],
    subIndustries: [{ key: 'intensive', label: 'Intensive courses', keywords: ['intensive', 'crash course'] }],
    commercialWeight: 0.6,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Prices', 'Book lessons', 'Instructors', 'Pass rates'],
    systemWeight: 0.7,
    systemUseCases: ['Alunos e etapas do processo', 'Agenda de aulas e instrutores', 'Pagamentos'],
  },
  {
    key: 'photography',
    label: 'Photographers',
    group: 'Creative',
    registryCodes: { GB: ['74201', '74202', '74209'], BR: ['7420001'] },
    keywords: ['photography', 'photographer', 'photo studio'],
    negativeKeywords: ['photo printing', 'camera shop'],
    subIndustries: [
      { key: 'wedding', label: 'Wedding photography', keywords: ['wedding'] },
      { key: 'commercial', label: 'Commercial photography', keywords: ['commercial', 'product'] },
    ],
    commercialWeight: 0.7,
    highTicket: true,
    bookingExpected: true,
    typicalServices: ['Portfolio', 'Packages and pricing', 'Check availability', 'About'],
    systemWeight: 0.6,
    systemUseCases: ['Ensaios agendados', 'Entrega de galerias', 'Contratos e pagamentos'],
  },
  {
    key: 'funeral',
    label: 'Funeral directors',
    group: 'Services',
    registryCodes: { GB: ['96030'], BR: ['9603304', '9603399'] },
    keywords: ['funeral', 'funeral director', 'memorial'],
    negativeKeywords: [],
    subIndustries: [{ key: 'prepaid', label: 'Prepaid plans', keywords: ['prepaid', 'pre-paid', 'funeral plan'] }],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Our services', 'Prices (Standardised Price List)', 'Prepaid plans', '24-hour contact'],
    systemWeight: 0.6,
    systemUseCases: ['Atendimentos e planos', 'Documentação', 'Fornecedores'],
  },
  {
    key: 'removals',
    label: 'Removals companies',
    group: 'Services',
    registryCodes: { GB: ['49420'], BR: ['4930204'] },
    keywords: ['removals', 'removal company', 'man and van', 'house moves', 'storage'],
    negativeKeywords: [],
    subIndustries: [{ key: 'storage', label: 'Storage', keywords: ['storage'] }],
    commercialWeight: 0.75,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Get a quote', 'Services', 'Storage', 'Areas covered', 'Insurance'],
    systemWeight: 0.75,
    systemUseCases: ['Orçamento por volume', 'Agenda de mudanças', 'Equipes e veículos'],
  },
  {
    key: 'architecture',
    label: 'Escritórios de arquitetura',
    group: 'Projetos',
    // No GB entry: this sector was never mapped to a SIC code here, and
    // inventing one so the list looks symmetrical would be worse than the gap.
    registryCodes: { BR: ['7111100', '7119703', '7119799'] },
    keywords: ['arquitetura', 'arquiteto', 'arquitetos', 'projeto arquitetonico', 'interiores'],
    negativeKeywords: ['arquitetura de software', 'arquitetura de sistemas'],
    subIndustries: [
      { key: 'residencial', label: 'Residencial', keywords: ['residencial', 'casa', 'apartamento'] },
      { key: 'corporativo', label: 'Corporativo', keywords: ['corporativo', 'comercial', 'escritorio'] },
      { key: 'interiores', label: 'Interiores', keywords: ['interiores', 'design de interiores'] },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Projetos', 'Portfólio', 'Etapas do trabalho', 'Orçamento'],
    systemWeight: 1.0,
    systemUseCases: [
      'Ordens de serviço e etapas de projeto',
      'Aprovações e revisões com o cliente',
      'Horas lançadas por projeto e por pessoa',
      'Plantas e documentos versionados',
      'Prioridade e prazo por tarefa',
    ],
  },
  {
    key: 'engineering',
    label: 'Engenharia',
    group: 'Projetos',
    registryCodes: { BR: ['7112000', '7119703', '7119799'] },
    keywords: ['engenharia', 'engenheiro', 'projeto estrutural', 'laudo tecnico', 'calculo estrutural'],
    negativeKeywords: ['engenharia de software'],
    subIndustries: [
      { key: 'estrutural', label: 'Estrutural', keywords: ['estrutural', 'calculo'] },
      { key: 'eletrica', label: 'Elétrica', keywords: ['eletrica', 'spda'] },
      { key: 'laudos', label: 'Laudos e perícias', keywords: ['laudo', 'pericia', 'art'] },
    ],
    commercialWeight: 0.9,
    highTicket: true,
    bookingExpected: false,
    typicalServices: ['Serviços', 'Obras e projetos', 'Laudos', 'Contato'],
    systemWeight: 1.0,
    systemUseCases: [
      'Ordens de serviço e responsável técnico',
      'ARTs, laudos e documentos por obra',
      'Medição e cronograma',
      'Horas por projeto',
    ],
  },
  {
    key: 'training_courses',
    label: 'Cursos e treinamentos',
    group: 'Educação',
    registryCodes: { BR: ['8599604', '8593700', '8541400', '8542200'] },
    keywords: ['curso', 'cursos', 'treinamento', 'capacitacao', 'escola tecnica', 'idiomas'],
    negativeKeywords: ['curso superior', 'faculdade', 'universidade'],
    subIndustries: [
      { key: 'profissionalizante', label: 'Profissionalizante', keywords: ['profissionalizante', 'tecnico'] },
      { key: 'idiomas', label: 'Idiomas', keywords: ['idioma', 'ingles', 'espanhol'] },
      { key: 'corporativo', label: 'Corporativo', keywords: ['in company', 'corporativo', 'gerencial'] },
    ],
    commercialWeight: 0.85,
    highTicket: false,
    bookingExpected: true,
    typicalServices: ['Cursos', 'Turmas e horários', 'Matrícula', 'Certificados'],
    systemWeight: 0.90,
    systemUseCases: [
      'Alunos, turmas e presença',
      'Matrículas e mensalidades',
      'Inadimplência e cobrança',
      'Material e certificados',
      'Desempenho por aluno',
    ],
  },
];

export const INDUSTRY_BY_KEY: ReadonlyMap<string, IndustryProfile> = new Map(
  INDUSTRIES.map((i) => [i.key, i]),
);

export function getIndustry(key: string): IndustryProfile | undefined {
  return INDUSTRY_BY_KEY.get(key);
}

export function industryLabel(key: string): string {
  return INDUSTRY_BY_KEY.get(key)?.label ?? key;
}

/** All registry codes for the given industries in the given country. */
export function registryCodesFor(industryKeys: string[], countryCode: string): string[] {
  const codes = new Set<string>();
  for (const key of industryKeys) {
    for (const code of INDUSTRY_BY_KEY.get(key)?.registryCodes[countryCode] ?? []) codes.add(code);
  }
  return [...codes].sort();
}

/** Industries usable in a country — i.e. those with codes or keywords for it. */
export function industriesForCountry(countryCode: string): IndustryProfile[] {
  return INDUSTRIES.filter((i) => (i.registryCodes[countryCode] ?? []).length > 0);
}

export const INDUSTRY_GROUPS: string[] = [...new Set(INDUSTRIES.map((i) => i.group))].sort();
